import Head from "next/head";
import Introduction from "../components/Introduction";
import ProjectsGrid from "../components/ProjectsGrid";
import { sanityClient } from "../sanity";

export default function Home({ projects }) {
  return (
    <div className="">
      <Head>
        <title>Noah Lissner</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="wrapper">
        <Introduction />
        <ProjectsGrid projects={projects} />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const query = `*[_type == "project"] {
    _id,
    title,
    slug,
  }`;

  const projects = await sanityClient.fetch(query);

  return {
    props: {
      projects,
    },
  };
};
